[server]
port = 8501
headless = true
enableCORS = false
maxUploadSize = 1000  # Taille max des fichiers en MB

[browser]
serverAddress = "localhost"

[theme]
base = "light"
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#31333F"
font = "sans serif"

[runner]
fastReruns = true
